# Generated by Django 5.0.2 on 2025-10-28 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='biometria_habilitada',
            field=models.BooleanField(default=False, verbose_name='Biometria Habilitada'),
        ),
        migrations.CreateModel(
            name='CredencialBiometrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.TextField(unique=True, verbose_name='ID da Credencial')),
                ('public_key', models.TextField(verbose_name='Chave Pública')),
                ('sign_count', models.IntegerField(default=0, verbose_name='Contador de Assinaturas')),
                ('nome_dispositivo', models.CharField(blank=True, max_length=100, verbose_name='Nome do Dispositivo')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True, verbose_name='Último Uso')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credenciais_biometricas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credencial Biométrica',
                'verbose_name_plural': 'Credenciais Biométricas',
                'ordering': ['-criada_em'],
            },
        ),
    ]
