# Generated by Django 5.0.2 on 2025-11-08 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_biometria_habilitada_credencialbiometrica'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField(help_text='Mensagem enviada pelo usuário', verbose_name='Mensagem do Usuário')),
                ('assistant_response', models.TextField(help_text='Resposta gerada pelo assistente', verbose_name='Resposta do Assistente')),
                ('intent', models.CharField(blank=True, help_text='Intenção identificada pela IA', max_length=50, null=True, verbose_name='Intenção')),
                ('transcribed_text', models.TextField(blank=True, help_text='Texto transcrito do áudio (se aplicável)', null=True, verbose_name='Texto Transcrito')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de Chat',
                'verbose_name_plural': 'Histórico de Chats',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usuario', '-created_at'], name='core_chathi_usuario_21d590_idx')],
            },
        ),
    ]
