# Generated by Django 5.0.2 on 2025-12-28 18:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chathistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('monthly_spending', 'Limite de Gastos Mensal'), ('monthly_saving', 'Meta de Economia Mensal'), ('category_limit', 'Limite por Categoria')], max_length=20, verbose_name='Tipo de Meta')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor da Meta')),
                ('mes', models.IntegerField(help_text='Mês da meta (1-12)', verbose_name='Mês')),
                ('ano', models.IntegerField(help_text='Ano da meta', verbose_name='Ano')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='core.casa', verbose_name='Casa')),
                ('categoria', models.ForeignKey(blank=True, help_text='Categoria específica (apenas para tipo category_limit)', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.categoria', verbose_name='Categoria')),
                ('criada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criada por')),
            ],
            options={
                'verbose_name': 'Meta Financeira',
                'verbose_name_plural': 'Metas Financeiras',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('casa', 'tipo', 'categoria', 'mes', 'ano')},
            },
        ),
    ]
